create table public.fw_asset_log (
  id uuid not null default gen_random_uuid (),
  ref_event_id uuid not null,
  ref_asset_id uuid not null,
  ref_assigner_id uuid not null,
  ref_updater_id uuid null default gen_random_uuid (),
  quantity_used integer not null,
  log_date date null,
  returned_date date null,
  ts_insert timestamp without time zone not null default CURRENT_TIMESTAMP,
  notes text null,
  updated_at timestamp without time zone null default now(),
  status character(1) not null,
  constraint fw_asset_log_pkey primary key (id)
) TABLESPACE pg_default;

create table public.fw_event_task (
  id uuid not null default gen_random_uuid (),
  ref_event_id uuid not null,
  ref_assigner_id uuid not null,
  ref_updater_id uuid null,
  created_at timestamp without time zone not null default CURRENT_TIMESTAMP,
  due_at timestamp without time zone null,
  completed_at timestamp without time zone null,
  notes text null,
  status character(1) null,
  constraint fw_event_task_pkey primary key (id)
) TABLESPACE pg_default;

create table public.fw_user_role (
  id bigint generated by default as identity not null,
  ref_user_id uuid not null default gen_random_uuid (),
  ref_role_id uuid not null default gen_random_uuid (),
  created_at timestamp with time zone not null default now(),
  status character(1) null,
  constraint fw_user_role_pkey primary key (id, ref_user_id, ref_role_id)
) TABLESPACE pg_default;

create table public.fw_user_volunteer (
  id uuid not null default gen_random_uuid (),
  ref_user_id uuid not null,
  ref_role_id uuid not null,
  nik character varying not null,
  full_name character varying not null,
  address text null,
  age int2vector null,
  email character varying not null,
  phone character varying null,
  url_photo character varying null,
  created_at timestamp without time zone not null default CURRENT_TIMESTAMP,
  updated_at timestamp without time zone null,
  status character(1) not null,
  constraint master_volunteer_pkey primary key (id)
) TABLESPACE pg_default;

create table public.fw_volunteer_event (
  id uuid not null default gen_random_uuid (),
  ref_event_id uuid not null,
  ref_volunteer_id uuid not null,
  registered_at timestamp without time zone not null default CURRENT_TIMESTAMP,
  verified_at timestamp without time zone null,
  ref_verified_id uuid null,
  notes text null,
  status character(1) not null,
  constraint fw_volunteer_event_pkey primary key (id)
) TABLESPACE pg_default;

create table public.list_data (
  id uuid not null default gen_random_uuid (),
  table_name character varying not null,
  column_name character varying not null,
  value character varying not null,
  description text null,
  ts_insert timestamp without time zone not null default CURRENT_TIMESTAMP,
  status character(1) not null,
  constraint list_data_pkey primary key (id)
) TABLESPACE pg_default;

create table public.master_asset (
  id uuid not null default gen_random_uuid (),
  name character varying not null,
  type character varying null,
  description text null,
  quantity integer null,
  available_quantity integer null,
  notes text null,
  created_at timestamp without time zone not null default CURRENT_TIMESTAMP,
  updated_at timestamp without time zone null,
  photo_url character varying null,
  status character(1) not null,
  constraint master_asset_pkey primary key (id)
) TABLESPACE pg_default;

create table public.master_event (
  id uuid not null default gen_random_uuid (),
  name character varying not null,
  description text null,
  notes text null,
  date_start date null,
  date_end date null,
  photo_url character varying null,
  created_at timestamp without time zone not null default CURRENT_TIMESTAMP,
  updated_at timestamp without time zone null,
  status character(1) not null,
  constraint master_event_pkey primary key (id)
) TABLESPACE pg_default;

create table public.master_role (
  id uuid not null default gen_random_uuid (),
  role_name character varying not null,
  role_description character varying null,
  status character(1) not null,
  constraint role_pkey primary key (id)
) TABLESPACE pg_default;

create table public.master_user (
  id uuid not null default gen_random_uuid (),
  username character varying not null,
  password character varying not null,
  created_at timestamp with time zone null default CURRENT_TIMESTAMP,
  updated_at timestamp without time zone null,
  status character(1) not null,
  constraint user_pkey primary key (id)
) TABLESPACE pg_default;